name: SCA - OWASP Dependency Check

on:
  push:
    branches: [ "main" ]

jobs:
  dependency-check:

    runs-on: ubuntu-latest

    steps:

    # Bước 1: tải source code
    - name: Checkout source code
      uses: actions/checkout@v4


    # Bước 2: cài Java 21
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21


    # Bước 3: build project bằng Maven
    - name: Build project
      run: mvn clean install -DskipTests


    # Bước 4: chạy OWASP Dependency Check
    - name: Run OWASP Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      id: depcheck
      with:
        project: "microShop"
        path: "."
        format: "HTML"
        out: "reports"


    # Bước 5: upload report để tải về
    - name: Upload report
      uses: actions/upload-artifact@v4
      with:
        name: SCA-report
        path: reports
